from damply import dirs as dmpdirs

# could alternatively pass this in the CLI via `--configfile $CONFIG/config.yaml`
# configfile: dmpdirs.CONFIG / "datasets" / "NSCLC-Radiomics_test.yaml"

include: "scripts/mit/run_mit.smk"

rule all:
    # Target rule
    input:
        readii_images_directory=expand(
            dmpdirs.PROCDATA / "{DATA_SOURCE}_{DATASET_NAME}" / "images" / "readii_{DATASET_NAME}",
            DATA_SOURCE=config["DATA_SOURCE"],
            DATASET_NAME=config["DATASET_NAME"]
        )


rule run_readii:
    input:
        mit_autopipeline_index=dmpdirs.PROCDATA / "{DATA_SOURCE}_{DATASET_NAME}" / "images" / "mit_{DATASET_NAME}" / "mit_{DATASET_NAME}_index.csv",
        mit_niftis_directory=dmpdirs.PROCDATA / "{DATA_SOURCE}_{DATASET_NAME}" / "images" / "mit_{DATASET_NAME}",
        dataset=config["DATASET_NAME"]
    output:
        readii_images_directory=directory(dmpdirs.PROCDATA / "{DATA_SOURCE}_{DATASET_NAME}" / "images" / "readii_{DATASET_NAME}")
    shell:
        "python scripts/readii/make_negative_controls.py --dataset {input.dataset} --overwrite True --seed 10"
