from damply import dirs as dmpdirs
from pathlib import Path
import pandas as pd

# could alternatively pass this in the CLI via `--configfile $CONFIG/config.yaml`
# configfile: dmpdirs.CONFIG / "datasets" / "NSCLC-Radiomics_test.yaml"

COMBINED_DATA_NAME = config["DATA_SOURCE"] + "_" + config["DATASET_NAME"]


rule run_mit_autopipeline:
    input:
        input_directory=dmpdirs.RAWDATA / COMBINED_DATA_NAME / "images" / config["DATASET_NAME"],
        mit_crawl_index=dmpdirs.RAWDATA / COMBINED_DATA_NAME / "images/.imgtools" / config["DATASET_NAME"] / "index.csv"
    output:
        mit_autopipeline_index=dmpdirs.PROCDATA / COMBINED_DATA_NAME / "images" / f"mit_{config["DATASET_NAME"]}" / f"mit_{config["DATASET_NAME"]}_index.csv",
        output_directory=directory(dmpdirs.PROCDATA / COMBINED_DATA_NAME / "images" / f"mit_{config["DATASET_NAME"]}")
    params:
        modalities=config["MIT"]["MODALITIES"],
        roi_match_map=config["MIT"]["ROI_MATCH_MAP"]
        roi_strategy=config["MIT"]["ROI_STRATEGY"]
    shell:
        """
        imgtools autopipeline {input.input_directory} {output.output_directory} \
        --modalities {params.modalities} \
        --roi-match-map {params.roi_match_map} \
        --roi-strategy {params.roi_strategy} \
        --filename-format "{{PatientID}}_{{SampleNumber}}/{{Modality}}_{{SeriesInstanceUID}}/{{ImageID}}.nii.gz"
        """


rule run_mit_index:
    input:
        dicom_dir=dmpdirs.RAWDATA / COMBINED_DATA_NAME / "images" / config["DATASET_NAME"]
    output:
        directory(dmpdirs.RAWDATA / COMBINED_DATA_NAME / "images/.imgtools" / config["DATASET_NAME"]),
        mit_crawl_index=dmpdirs.RAWDATA / COMBINED_DATA_NAME / "images/.imgtools" / config["DATASET_NAME"] / "index.csv"
    params:
        dataset_name= config["DATASET_NAME"]
    shell:
        """
        imgtools index --dicom-dir {input.dicom_dir} --dataset-name {params.dataset_name} --force
        """

