import os

# Path to output script to feed into LIFEx
output_script = ""
# Path to the lifex output (CSV file)
output_dir = ""
# Ensure the output directory exists
os.makedirs(output_dir, exist_ok=True)
# Path to the base directory containing patient folders
base_dir = ""

folder_names = os.listdir(base_dir)

with open(output_script, "w") as f:
    # Write header
    f.write("## LIFEx script generated by BHKLab\n\n")
    f.write("LIFEx.Output.Directory=" + output_dir + "\n\n")
    f.write("## _________________________________________________________________________________________________________________________\n\n")

    patient_idx = 0
    for folder in folder_names:
        folder_path = os.path.join(base_dir, folder)
        if os.path.isdir(folder_path):
            inner_folders = os.listdir(folder_path)
            for image in inner_folders:
                if image.startswith('CT'):
                  series_path = os.path.join(folder_path, image)
                elif image.startswith('RTSTRUCT'):
                  roi_path = os.path.join(folder_path, image)
                else:
                  continue
              
            # Write patient section
            f.write(f"## [Patient{patient_idx}] section\n\n")
            f.write(f"LIFEx.Patient{patient_idx}.Series0={series_path}\n")
            # There can be multiple Operations or ROIs
            f.write(f"LIFEx.Patient{patient_idx}.Series0.Operation0=Texture,true,false,false,1,3d,Absolute,10.0,400.0,-1000.0,3000.0,1.0,1.0,1.0\n")
            f.write(f"LIFEx.Patient{patient_idx}.Roi0={roi_path}\n\n")
            f.write("## _________________________________________________________________________________________________________________________\n\n")
            patient_idx += 1

print(f"Script written to {output_script}")