DATA_SOURCE: "TCIA"
DATASET_NAME: "CPTAC-PDA"

### CLINICAL VARIABLE INFORMATION ###
CLINICAL:
    FILE: ""
    OUTCOME_VARIABLES:
        time_label: ""
        event_label: ""
        convert_to_years: False
        event_value_mapping: {} # Event values should be in the order {0: Alive_value, 1: Dead_value}
    EXCLUSION_VARIABLES: {}

### MED-IMAGETOOLS settings
MIT:
    MODALITIES: 
        image: MR
        mask: RTSTRUCT
    ROI_STRATEGY: SEPARATE
    ROI_MATCH_MAP: GTV:.* # NOTE: there can be no spaces in KEY:ROI_NAME
        

### READII settings
READII:
    IMAGE_TYPES:
        regions:
            - "full"
            - "roi"
            - "non_roi"
        permutations:
            - "sampled"
        crop:
    TRAIN_TEST_SPLIT:
        split: False
        split_variable: {}
        impute: null

RANDOM_SEED: 10