DATA_SOURCE: "TCIA"
DATASET_NAME: "HEAD-NECK-RADIOMICS-HN1"

### CLINICAL VARIABLE INFORMATION ###
CLINICAL:
    FILE: "Copy of HEAD-NECK-RADIOMICS-HN1 Clinical data updated July 2020 2.csv"
    OUTCOME_VARIABLES:
        time_label: "overall_survival_in_days"
        event_label: "event_overall_survival"
        convert_to_years: True
        event_value_mapping: {} # Event values should be in the order {0: Alive_value, 1: Dead_value}
    EXCLUSION_VARIABLES: {}

### MED-IMAGETOOLS settings
MIT:
    MODALITIES: CT,RTSTRUCT
    ROI_STRATEGY: MERGE
    ROI_MATCH_MAP: # NOTE: there can be no spaces in KEY:ROI_NAME
        GTV:GTV-1

### READII settings
READII:
    IMAGE_TYPES:
        regions:
            - "full"
        permutations:
            - "original"
        crop:
    TRAIN_TEST_SPLIT:
        split: False
        split_variable: {}
        impute: null

RANDOM_SEED: 10