DATA_SOURCE: "TCIA"
DATASET_NAME: "HEAD-NECK-RADIOMICS-HN1"


CLINICAL_FILE: "Copy of HEAD-NECK-RADIOMICS-HN1 Clinical data updated July 2020 2.csv"

MIT_INDEX_FILE: "mit_betapipe_outputs_index.csv"

