DATA_SOURCE: "TCIA"
DATASET_NAME: "NSCLC-Radiomics"

### CLINICAL VARIABLE INFORMATION ###
CLINICAL:
    FILE: "NSCLC-Radiomics-Lung1.clinical-version3-Oct-2019.csv"
    OUTCOME_VARIABLES:
        time_label: "Survival.time"
        event_label: "deadstatus.event"
        convert_to_years: True
        event_value_mapping: {}
    EXCLUSION_VARIABLES: {}

### MED-IMAGETOOLS settings
MIT:
    MODALITIES:
        image: CT
        mask: RTSTRUCT
    ROI_STRATEGY: MERGE
    ROI_MATCH_MAP: # NOTE: there can be no spaces in KEY:ROI_NAME
        'GTV:GTV-1,gtv-pre-op'

### READII settings
READII:
    IMAGE_TYPES:
        regions:
            - "roi"
        permutations:
            - "shuffled"
        crop:
    TRAIN_TEST_SPLIT:
        split: False
        split_variable: {}
        impute: null

### Feature Extraction settings
EXTRACTION:
    METHOD: pyradiomics
    CONFIG: pyradiomics_original_single_feature.yaml

RANDOM_SEED: 10
