DATA_SOURCE: "TCIA"
DATASET_NAME: "NSCLC-Radiomics_test"

### CLINICAL VARIABLE INFORMATION ###
CLINICAL:
    FILE: ""
    OUTCOME_VARIABLES:
        time_label: ""
        event_label: ""
        convert_to_years: False
        event_value_mapping: {} # Event values should be in the order {0: Alive_value, 1: Dead_value}
    EXCLUSION_VARIABLES: {}

### MED-IMAGETOOLS settings
MIT:
    ROI_STRATEGY: MERGE
    ROI_MATCH_MAP:
        GTV:GTV-1
    MODALITIES: CT,RTSTRUCT
    

### READII settings
READII:
    IMAGE_TYPES:
        regions:
            - "roi"
        permutations:
            - "sampled"
        crop:
    TRAIN_TEST_SPLIT:
        split: False
        split_variable: {}
        impute: null

RANDOM_SEED: 10