DATA_SOURCE: "TCIA"
DATASET_NAME: "NSCLC-Radiomics"

### CLINICAL VARIABLE INFORMATION ###
CLINICAL:
    FILE: "NSCLC-Radiomics-Lung1.clinical-version3-Oct-2019.csv"
    OUTCOME_VARIABLES:
        time_label: "Survival.time"
        event_label: "deadstatus.event"
        convert_to_years: True
        event_value_mapping: {}
    EXCLUSION_VARIABLES: {}

### MED-IMAGETOOLS settings
MIT:
    MODALITIES: CT,RTSTRUCT
    ROI_STRATEGY: MERGE
    ROI_MATCH_MAP: # NOTE: there can be no spaces in KEY:ROI_NAME
        GTV:GTV-1

### READII settings
READII:
    IMAGE_TYPES:
        regions:
            - "full"
        permutations:
            - "original"
        crop:
    TRAIN_TEST_SPLIT:
        split: False
        split_variable: {}
        impute: null

RANDOM_SEED: 10