DATA_SOURCE: "TCIA"
DATASET_NAME: "RADCURE"

### CLINICAL VARIABLE INFORMATION ###
CLINICAL:
    FILE: "RADCURE_Clinical_v04_20241219.xlsx"
    OUTCOME_VARIABLES:
        time_label: "Length FU"
        event_label: "Status"
        convert_to_years: False
        event_value_mapping: {0: ['Alive'], 1: ['Dead']}
    EXCLUSION_VARIABLES: {'Ds Site': ['Sarcoma', 'Unknown', 'Paraganglioma', 'Salivary Glands', 'Other', 'benign tumor', 'Orbit', 'Lacrimal gland', 'Skin']}

### MED-IMAGETOOLS settings
MIT:
    MODALITIES: 
        image: CT
        mask: RTSTRUCT
    ROI_STRATEGY: MERGE
    ROI_MATCH_MAP: # NOTE: there can be no spaces in KEY:ROI_NAME
        KEY:ROI_NAME

### READII settings
READII:
    IMAGE_TYPES:
        regions:
            - "full"
        permutations:
            - "original"
        crop:


### Feature Extraction settings
EXTRACTION:
    METHOD: pyradiomics
    CONFIG: pyradiomics_original_single_feature.yaml

### Analysis settings
ANALYSIS:
    TRAIN_TEST_SPLIT:
        split_variable: 'RADCURE-challenge'
        train_label: 'training'
        test_label: 'test'
        impute: 'training'

RANDOM_SEED: 10
